# Generated by Django 5.1.2 on 2024-11-06 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateTimeField()),
                ('service_type', models.CharField(max_length=100)),
                ('comentar', models.CharField(max_length=255)),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipments')),
            ],
        ),
        migrations.CreateModel(
            name='Servises_Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('servises_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servises.servises')),
            ],
        ),
    ]
